#ifndef MEMORY_GLOBALVALUES_HPP
#define MEMORY_GLOBALVALUES_HPP

#define DEFAULT_STATUS_HEIGHT (qreal(20))
#define DEFAULT_STATUS_FONTPIXELSIZE (qreal(12))

#define DEFAULT_SPACING (qreal(0))
#define DEFAULT_MARGINS (qreal(10))
#define DEFAULT_EDGELENGTH  (qreal(8))
#define DEFAULT_LABELCOLOR  (Qt::white)
#define DEFAULT_LABEL  (QString())
#define DEFAULT_BORDERWIDTH  (qreal(0.5))

#define GLOBAL_BORDER_COLOR (Qt::gray)
#define GLOBAL_EMPTY_LABEL_COLOR (Qt::gray)


#endif // MEMORY_GLOBALVALUES_HPP

